# Generated by Django 5.0.4 on 2024-06-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=20)),
                ('units', models.IntegerField(default=0)),
                ('total_bills', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('reminder', models.TextField(default='not send', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_username', models.CharField(max_length=50, unique=True)),
                ('cus_pass', models.TextField(max_length=50)),
                ('meter_no', models.IntegerField(default=0)),
                ('phone_no', models.CharField(max_length=50, unique=True)),
                ('cus_bio', models.TextField(max_length=100)),
                ('cus_profile_img', models.ImageField(default='media\\icon\\person-man.webp', upload_to='profile_img')),
                ('address', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeterInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=0)),
                ('meter_location', models.TextField(max_length=100)),
                ('meter_type', models.CharField(max_length=50)),
                ('phase_code', models.CharField(max_length=50)),
                ('bill_type', models.CharField(max_length=50)),
                ('status', models.TextField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_file_charge', models.IntegerField(default=0)),
                ('meter_charge', models.IntegerField(default=0)),
                ('con_charge', models.IntegerField(default=0)),
                ('labour_charge', models.IntegerField(default=0)),
                ('adv_deposite', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_per_unit', models.IntegerField(default=0)),
                ('meter_rent', models.IntegerField(default=0)),
                ('service_charge', models.IntegerField(default=0)),
                ('service_tax', models.IntegerField(default=0)),
                ('swacch_bharat_cess', models.IntegerField(default=0)),
                ('fixed_tax', models.IntegerField(default=0)),
            ],
        ),
    ]
