# Generated by Django 5.0.4 on 2024-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_cus_pass_customer_cus_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_username', models.CharField(max_length=50, unique=True)),
                ('meter_no', models.IntegerField(default=0)),
                ('cus_fname', models.CharField(default='', max_length=50)),
                ('cus_lname', models.CharField(default='', max_length=50)),
                ('phone_no', models.CharField(max_length=50, unique=True)),
                ('cus_bio', models.TextField(max_length=100)),
                ('cus_profile_img', models.ImageField(default='media\\icon\\person-man.webp', upload_to='profile_img')),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cus_bio',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cus_fname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cus_lname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cus_profile_img',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='meter_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
