# Generated by Django 5.0.4 on 2024-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_reminder_customer_cus_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='meter_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='meter_no',
            field=models.IntegerField(default=0),
        ),
    ]
