# Generated by Django 5.0.4 on 2024-06-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_cus_last_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Cus_Profile',
        ),
    ]
