# Generated by Django 5.0.4 on 2024-06-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_profile_cus_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='phoneno',
            new_name='phone_no',
        ),
    ]
