# Generated by Django 5.0.4 on 2024-06-20 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_phoneno_reminder_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='reminderEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=0)),
                ('cus_username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('reminder_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reminderWA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=0)),
                ('cus_username', models.CharField(max_length=50, unique=True)),
                ('phone_no', models.CharField(max_length=50, unique=True)),
                ('message', models.CharField(max_length=100)),
                ('reminder_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='reminder',
        ),
    ]
