# Generated by Django 5.0.4 on 2024-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_reminderemail_reminderwa_delete_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterinfo',
            name='date_of_reg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reminderemail',
            name='reminder_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reminderwa',
            name='reminder_date',
            field=models.DateField(),
        ),
    ]
