# Generated by Django 5.0.4 on 2024-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_meterinfo_date_of_reg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='amountCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('month', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('total_Collection', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
