# Generated by Django 5.0.4 on 2024-06-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_amountcollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountcollection',
            old_name='amount',
            new_name='cus_amount',
        ),
        migrations.RenameField(
            model_name='amountcollection',
            old_name='month',
            new_name='cus_month',
        ),
        migrations.RenameField(
            model_name='amountcollection',
            old_name='status',
            new_name='cus_status',
        ),
        migrations.RenameField(
            model_name='amountcollection',
            old_name='year',
            new_name='cus_year',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='month',
            new_name='cus_month',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='status',
            new_name='cus_status',
        ),
        migrations.RenameField(
            model_name='cus_profile',
            old_name='status',
            new_name='cus_status',
        ),
        migrations.RenameField(
            model_name='meterinfo',
            old_name='status',
            new_name='cus_status',
        ),
        migrations.RenameField(
            model_name='reminderemail',
            old_name='status',
            new_name='cus_status',
        ),
        migrations.RenameField(
            model_name='reminderwa',
            old_name='status',
            new_name='cus_status',
        ),
    ]
