# Generated by Django 5.0.4 on 2024-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_empid_profile_meter_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meter_no',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
