# Generated by Django 5.0.4 on 2024-04-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=None, unique=True)),
                ('month', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeterInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=None, unique=True)),
                ('meter_location', models.TextField(max_length=100)),
                ('meter_type', models.CharField(max_length=50)),
                ('phase_code', models.CharField(max_length=50)),
                ('bill_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
