# Generated by Django 5.0.4 on 2024-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='meter_no',
        ),
        migrations.RemoveField(
            model_name='meterinfo',
            name='meter_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='meter_no',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
