# Generated by Django 5.0.4 on 2024-04-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_bill_meter_no_remove_meterinfo_meter_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reminder',
            field=models.TextField(default='not send', max_length=100),
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='status',
            field=models.TextField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
