# Generated by Django 5.0.4 on 2024-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_bill_meter_no_bill_total_bills_bill_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_no', models.IntegerField(default=0)),
                ('phone_no', models.CharField(max_length=50, unique=True)),
                ('user_bio', models.TextField(max_length=100)),
                ('user_profile_img', models.ImageField(default='media\\icon\\person-man.webp', upload_to='profile_img')),
                ('address', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='meter_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='utype',
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.TextField(max_length=100),
        ),
    ]
