# Generated by Django 5.0.4 on 2024-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customer_remove_profile_meter_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile_img',
            field=models.ImageField(default='media/icon/person-man.webp', upload_to='profile_img'),
        ),
    ]
