# Generated by Django 5.0.4 on 2024-06-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_id_alter_profile_user_profile_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MeterInfo',
        ),
        migrations.DeleteModel(
            name='ServiceCharge',
        ),
        migrations.DeleteModel(
            name='tax',
        ),
    ]
