# Generated by Django 5.0.4 on 2024-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_bill_delete_customer_delete_meterinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=50, null=None, unique=True),
        ),
    ]
